Upgrade to Vue3 + Vuetify 3 + Vite, with lots of other major improvements (#772)
* fix styling on loading create room overlay

* add LocaleSelector, fixes locale selector dropdown not working

* fix not being able to seek the video by dragging the slider

* UserList: fix missing icons preventing the user list from rendering completely

* UserList: fix typing for users prop

* finish typing for vuex store

* UserList: fix all typing errors

* remove dead code from vue 2

* RoomSettingsForm: remove some commented code

* CreateRoomForm: convert to composition api

* CreateRoomForm: fix form not updating modelValue

* add vitest, but most unit tests are still broken

* updated/removed some packages, makes vitest work more

* add vitest imports to all client side unit tests, fix YoutubePlayer tests

* kinda clean up/update AddPreview unit tests, but still not functional

* update vuetify to 3.0.1

* partially fix ClickToEdit component tests

* convert timestamp unit tests to typescript

* kinda update ClickToEdit unit tests

* update ProcessedText unit tests

* update ShareInvite unit tests

* remove a little more dead code

* adjust en locale

* completely rework how websocket connections are handled

also fix centering on RoomDisconnected overlay

* fix playback status not being sent

* update vue

* switch to sortablejs-vue3

* add a couple of minimal templates for components that aren't supposed to render

fixes a couple warnings in the console

* update ClickToEdit to vue 3 v-model

* move kick me button to debug card

* add optional reason to kickme message to make testing reconnect easier

* made websocket auto reconnect work with increasing delay on failed attempts

* remove some dead code and update comments for new connection code

* remove all dead old connection code

* remove @vue/compat because I'm actually not using it

* fix ClickToEdit not updating from external changes

* fix ClickToEdit not using the correct value when activated

* fix success toast not showing the correct icon

* add small border radius to toasts

* fix ShareInvite not having the clipboard icon anymore

* fix ShareInvite box not turning green when you click the copy button

* fix create room button in room list not working

* improve UserList styling a little bit

fix dropdown not being on the same line

* update docs for how to add a new locale

* update yarn lock

* add tslib to server dependencies

For some reason, when you prune all the dev dependencies the server would fail to start up.
It would print this error almost immediately:

```
Error: Cannot find module 'tslib'
```

Simply adding this package seems to fix it. Not quite sure why this is needed, but it fixes the problem.

* adjust add preview text box style

* update store type definitions and add a sass variable

* move some video controls to BasicControls

* move video progress slider from Room to VideoProgressSlider

* fix PermissionsEditor from being completely broken

* finish converting PermissionsEditor to composition api and typescript

also converted the unit tests for the component to typescript

* add doc comment to RoleGrants

* LoginForm: fix layout

* NavUser: fix a button's style

* improve typing around connection message handlers

* ClosedCaptionsSwitcher: adjust styling and convert to vuetify 3

* adjust style on the remaining video controls

* make tabs orange again

* fix config for vuetify style overrides

* set up a couple of new custom themes, deepgreen and deepblue

* make ProcessedText use .text-primary class instead

* make UserList respect theme colors a little better

* RoomSettingsForm: fix queue mode drop down not rendering the same as the visibility one

* add SET_FULLSCREEN mutation

* fix client not respecting seeks to position 0 if the video is playing

backportable

* fix prod check

* YoutubePlayer: remove a log

* fix navbar buttons being centered

* update cypress

* add types for uuid package, adjust cypress tsconfig

* update create-room test suite

* switch permissions e2e suite to typescript, still failing

* fix permissions e2e test suite

* update playback e2e test suite

I had to add a workaround in order for custom command ottRequest to not cause type errors

* update room-settings e2e test suite

* update user-login e2e test suite

* make the ott-common package imported correctly instead of doing some wacky shit

I have no idea why I didn't do it like this in the first place...

* client: set up cypress for component testing, kinda sorta, doesn't really work

* fix a couple more imports

* client: finish setting up cypress component testing, it actually works now

* add some more tests to ClickToEdit e2e suite, fix some styling

* add a couple component tests for RoomSettingsForm

* update uuid package

* WIP: add cypress e2e tests to CI

* add some component tests for AddPreview

* adjust vite config to fix cypress in CI?

* format

* adjust some assertions

* format

* adjust assertions in room-setttings e2e suite

* remove old AddPreview unit tests

* add node 18.x to CI workflow

* ShareInvite: replace unit tests with e2e component tests

also grab short url from store instead of directly accessing import.meta.env

* format, fix typescript errors

* update eslint-plugin-vue and fix some of the lints

* fix some more lints related to vue3

* fix remaining lint errors

* fix lint-ci script

* force disbable vite hmr when running component tests

seems to improve flakeyness

* fix another lint

* skip running clipboard test on firefox because it doesn't have `navigator.clipboard`

* skip some ClickToEdit tests on firefox

these tests *always* fail in run mode in firefox. they pass in open mode,
but CI doesn't use open mode.

* remove `@cypress/skip-test` because it's not needed

* ClickToEdit tests: add assertion for cursor style

* server: fix syncUser sending out the wrong grant mask

* add a data-cy attribute

* RoomSettingsForm: fix auto skip checkbox not being disabled if you don't have permission

* Notifier: add component tests

* remove old Notifier tests

* make overlay scrim background black instead of white

* fix save room settings button not being sticky to the bottom

* adjust .no-video styling for light and dark themes

* ToastNotification: add elevation, fix extra long toasts not increasing height

* Notifier, ToastNotification: adjust styling

* ToastNotification: fix close button not appearing on success/error toasts

* Notifier: add e2e test for toast width and height

* rename `SHORT_URL` to `OTT_SHORT_URL_HOSTNAME` and made sure it gets into production builds

* fix a few minor lint warnings

* remove QuickRoom

* make Playground only accessible in dev mode

* prune some unused packages

* update typescript to 4.5.5

* prune babel-jest

* remove dead jest configs used for client unit tests

* update ts-node

* server: move environment variable validation to ott-config module

* server: convert app.js to typescript

* fix User and Room models overshadowing sequelize getters and setters

* add e2e test to verify that unloading and loading permanent rooms works

* e2e tests: add retries for cypress run mode only

* split cypress component test jobs from e2e test jobs

* server: fix unit tests being completely broken, now they are just kinda broken

* server: fix imports in unit tests

* actually fix the sequelize overshadowing warning and maintain typings

* server: fix another import in unit tests, whoops

* client: gut some unit tests that were not useful, or already covered better by e2e tests

* client: make VideoQueueItem unit tests not trip up jest, but most tests are still skipped

* client: make Room unit tests not trip up vitest

* format

* client: VideoQueueItem: add component tests and remove old unit tests

* client: VideoQueueItem: add some more component tests for adding and removing videos

* client: skip more unit tests until I have good replacements as component tests

* client: refactor useConnection to not require a plugin

* client: have api fall back to useConnection if it can

* client: actually, you do need a plugin, so fuck me i guess

* add new useRoomApi composable

* make it possible to mock websocket usage for component tests

* client: Chat: add some component tests

* client: remove hack from Room view that passes chat messsages to chat component because it's no longer needed

* fix a couple type errors

* client: remove most usages of old `@/util/api`

only usages that remain are in Room view

* client: OmniPlayer: convert to typescript

slightly reduces warnings and errors during normal usage

extremely experimental, and will need plenty of more testing

* client: OmniPlayer: refactor how events are emitted so Room has to manage playback status less

* fix/adjust some lints

* remove --if-present from ci build

* VideoQueueItem: remove broken unit test

* update dockerfiles to node 18 images

* check if performance api is available before using it

* fix e2e jobs not having ts-node for some reason

* update cypress

* remove cypress config that doesn't help flakiness

* server: add a dev endpoint to set the api key for e2e tests

* make e2e test set admin api key so it passes in CI

* client: fix promotions and demotions not working

* fix deepblue and deepgreen themes looking kinda goofy

* fix volume and media progress sliders not adhering to the theme's primary color

* fix chat not using theme colors

* change scss vars to be aliases of the vuetify css vars they provide

* make the theme selector use the theme for each of the buttons so you can kinda preview the theme before saving

* replace deepgreen with deepred

* add themes to UI

* adjust deepblue theme

* client: dynamically create list of all themes for verification

* client: VideoProgressSlider: add a missing type

* client: add a theme var media-control-surface and apply it to basic controls

* client: move timestamp display into new component TimestampDisplay

* client: add media-control to ClosedCaptionsSwitcher

* client: move layout switcher and fullscreen button to new LayoutSwitcher component

* client: make chat activate button always white

* format

* client: Room: remove usages of deprecated GrantChecker class

* client: small fix to roomapi.kickMe() typing

* client: add some props to OttRoomConnection interface

* client: convert Room view to composition api

fuckin finally able to do this

* client: move room keyboard shortcuts to be handled by `useRoomKeyboardShortcuts()`

* client: show client ids in user list in debug mode

* client: clear message handlers when ServerMessageHandler is unmounted

* client: UserList: use v-chip instead of custom style

* format

* client: a11y: slightly improve contrast for a couple elements

* client: a11y: add some aria-labels

* client: ally: add some more aria stuff

* client: remove dead util/api helper

* client: small refactor to room state/store

* client: make WorkaroundPlaybackStatusUpdater unsubscribe on unmount

* client: wrap OmniPlayer with suspense so we can show a loader

* client: slightly trim the number of bytes in the AddPreview component for production builds

* client: slightly adjust video controls showing and hiding behavior

* format

* server: adjust socket disconnect behavior

* fix docker files

* add unit tests for keyboard shortcut helper

* remove some dead code

* update vuetify to 3.0.3

* replace custom css class with v-chip

* client: reset reconnect attempts on successful connect

* client: fix rerender triggered on reconnect causing video player to flicker

* client: adjust no-video styling for deepblue and deepred

* fix minor lints

* client: add timestamp seek preview tooltip when you hover over the video progress slider

* docs: update readme with how to run component/e2e tests

* client: auto unbind key bindings when the calling component is unmounted

* VideoQueueItem: add a component test

* add cypress-real-events

* Chat: make sure new chat messages are visible, regardless of message count

* Chat: allow long lines to be broken anywhere, other minor margin/padding adjustments

* Chat: add scroll to bottom button when you are scrolled up

* update to cypress 12

* ProcessedText: add showAddQueueTooltip prop, refactor failing unit test into component test

* update yarn lock

* remove optic 10 packages from dependencies

* docs: add optic ignore paths

* docs: update api spec, format

* server: remove unnecessary counters field from /api/status

also document /api/status and /api/status/metrics

* client: hack: hide nav bar in full screen mode

* fix faq page

* remove support for node 14 because its old af

* update readme with min node version

* update cypress to 12.3.0

* update @cypress/vue to 5.0.3

* CI: change e2e test browser list to just "electron"

* remove unused .player css class

* disconnect resize observer before unmounting youtube player

* VideoQueue: remove off-by-one hack

* update vite to 4.0.4

* update vuetify to 3.1.2

* update ResizeObserver mock

* change browser list for component e2e tests to just electron

* don't download node modules artifact for e2e tests

* add setup node in e2e test pipeline

* set up build essentials in e2e pipeline

* add check for resize observer before disconnecting it

* add sudo

* switch back to downloading node modules artifact

* pin node version for e2e tests

* ci: comment out cypress docker containers to see if it still breaks

* ci: e2e: change redis host to localhost